name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #  Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #  Build de l’image avec tag unique (commit SHA)
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-docker: latest .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-docker:${{ github.sha }} .

      # Push des deux tags
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/demo-docker:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/demo-docker:${{ github.sha }}
